//
//  Stylesheet.swift
//  JoyCo
//
//  Created by Cole Roberts on 10/31/23.
//

import Foundation
import SwiftUI

/// A very naive approach to a stylesheet that can be utilized
/// in SwiftUI views, centralizing access to common
/// design-related values like spacings, colors, typography etc.
///
/// In reality, this should probably be automatically generated by a closely
/// curated design token system.
struct Stylesheet {
    enum Colors {
        /// Fetch yellow
        /// - r: 255, g: 169, b: 0
        static let brandYellow: Color = .init(red: 255.0/255.0, green: 169.0/255.0, blue: 0/255.0)
    }
    
    enum Corners {
        /// - 4pt -
        static let small = 4.0
        
        /// - 6pt -
        static let medium = 6.0
    }
    
    enum Images {
        /// - 80pt -
        static let thumbnail = 80.0
        
        // - 224pt -
        static let hero = 224.0
    }
    
    enum Spacings {
        /// - 4pt -
        static let tiny = 4.0
        
        /// - 8pt -
        static let small = 8.0
    
        /// - 16pt -
        static let medium = 16.0
        
        /// - 24pt -
        static let large = 24.0
    }
}
